version: '3.0'

services:
   wordpress:
      container_name: wordpress
      volumes: 
        - ./wordpress:/var/www/html
      ports:
        - 8080:80
      image: wordpress:latest
      environment:
        WORDPRESS_DB_HOST: mariadb:3306
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: 517517
        WORDPRESS_DB_NAME: wordpress
      networks:
        - mysql_default
networks:
  mysql_default:
    external: true