version: "3.0"

services: 
    ldap:
        container_name: openldap
        image: osixia/openldap
        ports: 
            - 389:389
            - 636:636
        environment:
            - LDAP_ORGANISATION=example
            - LDAP_DOMAIN=example.com
            - LDAP_ADMIN_PASSWORD=123456
        restart: always
