version: "3.0"

services: 
    etcd:
        container_name: etcd
        image: elcolio/etcd
        volumes: 
            - 
        ports: 
            - 
        environment:
            - 
        restart: always