version: "3.0"

services: 
    redis:
        container_name: redis
        image: redis
        volumes: 
            - /data/docker_volume:/data
        ports: 
            - 6379:6379
        