version: "3.0"

services:
  mysql:
    container_name: mariadb
    image: mariadb
    volumes:
      - /d/langenv/wsl/data/volume/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=517517
    restart: always