version: '2'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh'
      #restart: always
      hostname: '39.104.107.35'
      ports: 
          - "9999:80"
#          - "9443:443"
 #         - "3333:22"
      volumes:
        - /docker/volume/gitlab2/config:/etc/gitlab
        - /docker/volume/gitlab2/data:/var/opt/gitlab
        - /docker/volume/gitlab2/logs:/var/log/gitlab
      networks:
         gitlab_net:
      environment:
         TZ: 'Asia/Shanghai'
networks:
    gitlab_net:
