version: "3.0"

services: 
    jellyfin:
        container_name: jellyfin
        hostname: jellyfin
        image: jellyfin/jellyfin
        volumes: 
            - /jellyfin/config:/config
            - /mnt/d/langenv/wsl/data/volume/jellyfin/media:/media
        ports: 
            - 8096:8096
        restart: always
